# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_unique_ind <- function(df) {
    .Call(`_exondiscovery_get_unique_ind`, df)
}

filter_exon_length <- function(df, max_length) {
    .Call(`_exondiscovery_filter_exon_length`, df, max_length)
}

pred_exon_coord <- function(df) {
    .Call(`_exondiscovery_pred_exon_coord`, df)
}

